#### [REDHAT] Check if reboot is needed ####
---
- name: "[REDHAT] Check if needs-restarting is installed"
  stat:
    path: /usr/bin/needs-restarting
  register: redHatNeedsRestartingInstalled
  when: ansible_facts['os_family'] == "RedHat"

- name: "[REDHAT] run needs-restarting"
  become: true
  shell: needs-restarting -r
  register: redHatNeedsRestartingStatus
  when: redHatNeedsRestartingInstalled.stat.exists
  failed_when: redHatNeedsRestartingStatus.rc <=2

- name: "[RedHat] Reboot Required"
  debug:
    msg: "Reboot is Required on {{ ansible_hostname }}"
  when: redHatNeedsRestartingStatus.rc != 0 and "Reboot is required" in redHatNeedsRestartingStatus.stdout

  #when: redHatNeedsRestartingStatus.rc == 1
  #when: "'Reboot is required' in redHatNeedsRestartingStatus.stdout"

- name: "[RedHat] Reboot Not Required"
  debug:
    msg: "Reboot is Not Required on {{ ansible_hostname }}"
  when: redHatNeedsRestartingStatus.rc == 0 and "Reboot is required" not in redHatNeedsRestartingStatus.stdout