#### [REDHAT] Check if reboot is needed ####
---
- name: "[REDHAT] Check if needs-restarting is installed"
  stat:
    path: /usr/bin/needs-restarting
  register: redHatNeedsRestartingInstalled
  when: ansible_facts['os_family'] == "RedHat"

- name: install yum-utils, if not installed
  yum:
    name: yum-utils
    state: present
  when: ansible_facts['os_family'] == "RedHat" and not redHatNeedsRestartingInstalled.stat.exists

- name: "[REDHAT] run needs-restarting"
  shell: needs-restarting
  register: redHatNeedsRestartingStatus
  when: redHatNeedsRestartingInstalled.stat.exists

- name: "[RedHat] Reboot Required"
  debug:
    msg: "Reboot is Required on {{ ansible_hostname }}"
  when: redHatNeedsRestartingStatus.rc == 1