# Playbook that updates ClamAV definitions
---
- name: Check for ClamAV
  stat:
    path: "/usr/bin/clamscan"
  register: cl_service_status

- name: Update clamav
  command: /usr/bin/freshclam --verbose
  register: clamout
  when: cl_service_status.stat.exists

- name: Output from CLAMAV-command
  debug: msg="{{ clamout.stdout_lines }}"
  when: clamout.stdout_lines is defined