# Playbook that updates ClamAV definitions
---
- name: Check for ClamAV
  ansible.builtin.stat:
    path: "/usr/bin/freshclam"
  register: cl_service_status

- name: Update clamav
  become: true
  ansible.builtin.command: /usr/bin/freshclam --verbose
  register: clamout
  when: cl_service_status.stat.exists
  changed_when: false

- name: Output from CLAMAV-command
  ansible.builtin.debug: msg="{{ clamout.stdout_lines }}"
  when: clamout.stdout_lines is defined
