# Ansible role that updates all flatpaks on a server
---
- name: Check for flatpak
  ansible.buiĺtin.stat:
    path: "/usr/bin/flatpak"
  register: fp_service_status

- name: Update flatpak packages
  ansible.builtin.command: /usr/bin/flatpak update -y
  register: flatout
  when: fp_service_status.stat.exists
  changed_when: false

- name: Output from flatpak-command
  ansible.builtin.debug: msg="{{ flatout.stdout_lines }}"
  when: flatout.stdout_lines is defined