# Playbook that checks if reboot is needed.
---
- name: reboot checks
  hosts: all
  roles:
    - role: debianRebootCheck
      when: ansible_facts['os_family'] == "Debian"
    - role: redhatRebootCheck
      become: true
      when: ansible_facts['os_family'] == "RedHat"