services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  postgres:
    restart: unless-stopped
    image: postgres:14
    hostname: postgres
    volumes:
      - /opt/podmnts/semaphore-postgres:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: semaphore
      POSTGRES_DB: semaphore
  # if you wish to use postgres, comment the mysql service section below
  #mysql:
    #restart: unless-stopped
    #image: mysql:8.0
    #hostname: mysql
    #volumes:
    #  - semaphore-mysql:/var/lib/mysql
    #environment:
    #  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    #  MYSQL_DATABASE: semaphore
    #  MYSQL_USER: semaphore
    #  MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: postgres # for mysql, change to: mysql
      SEMAPHORE_DB_PORT: 5432 # change to 3306 for mysql
      SEMAPHORE_DB_DIALECT: postgres # for mysql, change to: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: 2QHh/vS7TcMJuwE397lpedf/yIQfZVMgY3gqr0z9v0Q=
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
    depends_on:
      - postgres # for mysql, change to: mysql
#volumes:
#  semaphore-postgres: # to use mysql, switch to: semaphore-mysql